### ISSUE TITLE
can not run configure

### ISSUE THREAD

**Issue by vyrus001** [michenriksen/gitrob#96] opened 2016-11-09 18:00 UTC
all gems installed (including gitrob). Postgresql database created. When i run gitrob configure, i get this

gitrob configure
/var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api/api.rb:301:in `namespace': namespace 'say' is already defined (ArgumentError)
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api/client.rb:61:in `<class:Client>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api/client.rb:4:in `<module:Github>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api/client.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api.rb:78:in `block in require_all'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api.rb:77:in `each'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api.rb:77:in `require_all'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api.rb:113:in `<module:Github>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.5/lib/github_api.rb:15:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/exe/gitrob:3:in `<top (required)>'
	from /usr/local/bin/gitrob:23:in `load'
	from /usr/local/bin/gitrob:23:in `<main>'

uname -a
Linux hawk 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

**Comment by jeffxf** [comment] 2017-01-11 19:27
The issue is caused by having github_api v 0.14 so you can fix this by uninstalling the github_api gem you currently have and installing 0.13 instead by running these commands:
`gem uninstall github_api`
`gem install github_api -v 0.13`

**Comment by IridiumHack** [comment] 2017-01-12 17:37
Thank you for your help!

**Comment by jeunito** [comment] 2017-01-13 00:05
I tried @jeffxf's fix too and it worked for me. Thanks.

**Comment by jeunito** [comment] 2017-01-13 00:17
I have made a PR that pins the github_api gem to 0.12. I hope it gets merged.

**Comment by jeffxf** [comment] 2017-01-25 19:07
@jeunito I didn't look into what changed between 0.12 and 0.13 but changing that pull request to have it use 0.13 might be a good idea since it is the most recent version that works.

**Comment by jeunito** [comment] 2017-01-26 18:10
@jeffxf ok I think I may have seen issues with 0.13 too but I'll check again.

**Comment by jeunito** [comment] 2017-01-31 01:21
@jeffxf I can confirm that this works on 0.13

**Comment by jeunito** [comment] 2017-01-31 20:28
@jeffxf I have updated the PR to use 0.13 instead.

**Comment by michenriksen** [comment] 2017-04-09 08:14
This issue is fixed in version 1.1.1

**Closed by michenriksen** 2017-04-09 08:14 UTC
